curFig  = figure( 'units' , 'normalized' , 'position' , [ 0.5 0 0.5 1 ] ) ;
curAxes =   axes( 'units' , 'normalized' , 'position' , [ 0 0.5 1 0.5 ] ) ;
curPanel = uipanel( 'units' , 'normalized' , 'position' , [ 0 0 1 0.5 ] ) ;
hold all , axis manual
plotButton  = uicontrol( 'style' , 'pushbutton' , 'parent' , curPanel , ...
    'units' , 'normalized' , 'position', [ 0.00 .3 .5 .6 ] , 'string' , ...
    'Plot' , 'Callback' , 'plot( [ 0 1 ] , [ 0 get(angleSlider,''value'') ] )' ) ;
clearButton = uicontrol( 'style' , 'pushbutton' , 'parent' , curPanel , ...
    'units' , 'normalized' , 'position', [ 0.5 .3 .5 .6 ] , 'string' , ...
    'Clear', 'Callback' , 'cla' ) ;
angleSlider = uicontrol( 'style' , 'slider'     , 'parent' , curPanel , ...
    'units' , 'normalized' , 'position', [ 0 0.1 1 .1 ] , 'value' , 0.5 ) ;
