
function addButtons(obj)

curFuncs = { ...
    { @(src,event)saveLoadFractal(obj) } , ...
    { @(src,event)changeName(obj) } , ...
    { @(src,event)alterSettings(obj,false) } , ...
    { @(src,event)drawSeed(obj) } , ...
    { @(src,event)plantSeed(obj) } , ...
    { @(src,event)growFractal(obj) } , ...
    } ;

curNames = { ...
    '<html><center>Load<br>Fractal' , ...
    '<html><center>Change<br>Name' ...
    '<html><center>Alter<br>Settings' , ...
    '<html><center>Draw<br>Seed' , ...
    '<html><center>Scrap<br>Fractal' , ...
    '<html><center>Grow<br>Fractal' , ...
    } ;

nButtons = length( curFuncs ) ;

for i = 1 : nButtons
    
    obj.curButtons(i) = uicontrol(   ...
        'style'     , 'pushbutton' , ...
        'parent'    , obj.curPanel , ...
        'fontunits' , 'normalized' , ...
        'fontsize'  , .25 , ...
        'units'     , 'normalized' , ...
        'position'  , [ 0 1-i/nButtons 1 1/nButtons ] , ...%         'position'  , [ 0 (i-1)/nButtons 1 1/nButtons ] , ...
        'string'    , curNames{i}  , ...
        'callback'  , curFuncs{i}  ) ;
    
end

set( obj.curButtons(end) , 'style' , 'togglebutton' )

end